version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: container-api-generica-spring-boot
    ports:
      - "8080:8080"
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: '2.0'
        reservations:
          memory: 256M
          cpus: '1.0'
    environment:
      #SPRING_PROFILES_ACTIVE: ${SPRING_PROFILES_ACTIVE}
      SPRING_DATASOURCE_URL: ${SPRING_DATASOURCE_URL}
      SPRING_DATASOURCE_USERNAME: ${SPRING_DATASOURCE_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
    volumes:
      - /data/api-generica-spring-boot/logs:/app/logs
      - /data/api-generica-spring-boot/volumes:/app/data
    networks:
      - minha_rede_dev
networks:
  minha_rede_dev:
    external: true

