version: '3.8'

services:
  db:
    image: postgres:17.0
    container_name: container-api-postgres-db-generic
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: '0.5'
        reservations:
          memory: 256M
          cpus: '0.25'
    environment:
      POSTGRES_DB: generic_db_teste
      POSTGRES_USER: dev_generic_teste
      POSTGRES_PASSWORD: senha123
    ports:
      - "5432:5432"
    networks:
      - minha_rede_dev
networks:
  minha_rede_dev:
    external: true