CREATE SCHEMA IF NOT EXISTS "TO_DO_LIST";

CREATE TABLE  "public"."TAB_USER" (
                                      "ID_USER" INT8 GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                      "FULL_NAME" VARCHAR (100) NOT NULL,
                                      "USER_NAME" VARCHAR (20) NOT NULL,
                                      "password" VARCHAR (20) NOT NULL
);

CREATE TABLE "public"."TAB_TASK" (
                                     "ID_TASK" INT8 GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                     "TITLE_TASK" VARCHAR (100),
                                     "DESCRIPTION" VARCHAR (100),
                                     "DATE_CREATE" TIMESTAMP,
                                     "STATUS" VARCHAR(15)

);